### ISSUE TITLE
Strange error when unsupported method name is passed to nestle.sample()

### ISSUE THREAD

**Issue by bek0s** [kbarbary/nestle#26]
Hello,

If I pass an unsupported method to `nestle.sample()`, Nestle is trying to throw an exception like this:
`raise ValueError("Unknown method: {:r}".format(method))`

The above fails in Python3.7 with the following message: 

> ValueError: Unknown format code 'r' for object of type 'str'

What is `:r` supposed to do anyway?

**Comment by kbarbary** [comment]
This should be `{!r}` rather than `{:r}`. `!r` causes the formatter to use `repr` instead of `str`, so the method appears in quotes. I didn't write a test for this exception!

**Comment by kbarbary** [comment]
closed by #27
